### ISSUE TITLE
Edit-Post-Story

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#10]
Rationale:
If a comment is made about an experiment we want to have the maker of that post to make changes to the post this includes the deletion of the post in general. The make of the experiment might also want to make comments and discuss the current experiment with some of the crowed-experimenters about the experiment in general. 

Story Points:
2

Risk Level:  
Low

**Comment by NickNissen** [comment]
This functionality may be a discussion point with the project owner
