### ISSUE TITLE
Run All Tests on PRs

### ISSUE THREAD

**Issue by giancarlopernudisegura** [CMPUT301W21T03/Experiment-Automata#112]
Rationale:

Create a CI like in lab 8 using travis-ci to run the android studio tests on all pull requests. This will make the job for reviewers easier.

Story Points:
3

Risk Level:
Low

**Comment by TurtleSquad007** [comment]
Do we need this anymore?

**Comment by TurtleSquad007** [comment]
Don't need this anymore
