### ISSUE TITLE
Create-User-Story (US 04.01.01)

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#12]
US 04.01.01
As an owner or experimenter, I want a profile with a unique username and my contact information.

Rationale:
Since we need users to use out applications and that is the demand of the customer, we need a way to make users. The goal is to make a user in such a way where the primary key is the user-name that we generate using something like the UUID class that is in built in the Java libraries. Here we also need to set the permissions as they are required by the customer, for example we cannot a crowed experimenter do the same things as the head/owner of the experiment. 

Story Points:
4

Risk Level: 
High

**Comment by NickNissen** [comment]
A Conversation with the product owner is required to gather more specific details around the desired functionality of user creation.
