### ISSUE TITLE
Subscribe-Story (US 01.04.01)

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#13]
US 01.04.01
As an owner or experimenter, I want to subscribe to an experiment to participate in it.

Rationale:
Allow the user to subscribe to add experiments that they wish to subscribe to. If the user makes an experiment they are initially subscribed to that experiment itself.  Allowing those users that are subscribed to it participate in the experiment that the user subscribed to. For example I wish to participate in the "rain" experiment, once I subscribe I can now participate in it. 

Story Points:
3

Risk Level: 
Medium

**Comment by NickNissen** [comment]
Decision needs to be made as to the relationship between experiments and experimenters, should there be a separate "Subscription" class to hold this relationship?

**Comment by musichead42** [comment]
Pull request above creates an activity with all the information for the subscription fragment. @giancarlopernudisegura and I have discussed doing some refactoring so that it works with the main-screen branch.
