### ISSUE TITLE
Refactor code to use design patterns discussed in class

### ISSUE THREAD

**Issue by musichead42** [CMPUT301W21T03/Experiment-Automata#132]
- We should look into using the factory design pattern anytime we have a switch case for the trial or experiment types. 
- Look into using the command pattern, composite pattern, template method pattern, and adapter pattern where applicable.

**Comment by giancarlopernudisegura** [comment]
Should we make a trial result hold a generic type that the trial child classes implement?

**Comment by TurtleSquad007** [comment]
Currently Trial is generic(abstract). What do you mean?

**Comment by TurtleSquad007** [comment]
Oh I see. Yeah I agree with you 100%.

**Comment by giancarlopernudisegura** [comment]
I'm working on it in [trial-refactoring](https://github.com/CMPUT301W21T03/Experiment-Automata/tree/trial-refactoring).

**Comment by giancarlopernudisegura** [comment]
@CMPUT301W21T03/main By that logic then, should Experiments be a generic abstract too?

**Comment by TurtleSquad007** [comment]
I would say yes, since it already kinda works like that. Why not go all the way.
