### ISSUE TITLE
Subscriptions-Story

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#14]
Rationale:
The goal here to show a list of the experiments our current experimenter has the ability to participate in, including those that the current owner has made. Here we must also give the ability for each experimenter to leave the experiments that they are subscribed to so we're giving them that ability here where they can see all of the subscriptions that have been made. 

Story Points:
2

Risk Level: 
Low

**Comment by musichead42** [comment]
The code that worked on this issue was accidentally pushed to main, so it's not a part of the subscription fragment pull request. Here was the commit that addressed this issue: https://github.com/CMPUT301W21T03/Experiment-Automata/commit/00cf4c3769595935a062b2f9adad1b6624e3e8de
