### ISSUE TITLE
Make-QR-Story (US 03.01.01)

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#17]
US 03.01.01
As an experimenter, I want to be able to generate QR codes that I can print for a specific experiment and trial result (for instance PASS for a binomial trial I subscribed to). 

Rationale:
The customer has asked that we make the ability to attach QR codes to an experiment. To do this we have to provide someway to link experiment to a QR code. Here we make QR codes that can be attached to an experiment, so that they can be searched for and displayed to the customer when presenting QR codes to the app. 

Story Points:
8 - because no-one on the team has dealt with QR codes on android, more than likely this can be amended to 5 with some research

Risk Level:
Medium

**Comment by NickNissen** [comment]
From Eclass:
1) a count based trial can have 1 QR code to be scanned to indicate something was seen
1) a binomial trial will have at least 2 QR codes. 1 for success, 1 for failure.
2) is says experimenter so it means anyone participating in the experiment.
