### ISSUE TITLE
Unpublish-Users-Story

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#20]
Rationale:
We need to be able to remove experiments from the DB we have set up. So the goal is to remove the selected experiment from the DB. 

Story Points:
NaN -> Shouldn't be too hard to have set up about an hour at most. 

Risk Level:
NaN -> Since this is a must I don't anticipate this being not being done so the risk is low.

**Comment by NickNissen** [comment]
Not required at this time
