### ISSUE TITLE
View-Current-User-Experiments-Story

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#22]
Rationale:
We need someway to view the current set experiments published by the current user. This is to allow the current user to see the data and experiment they might have unsubscribed or to monitor experiment posts that have been made for their experiments and so on.  

Story Points:
2

Risk Level: 
High

**Comment by TurtleSquad007** [comment]
Wasn't this already done by @giancarlopernudisegura and myself?

**Comment by giancarlopernudisegura** [comment]
Right now we have a screen that shows a list of owned experiments if that's what you're referring to.

**Comment by TurtleSquad007** [comment]
Yeah. Which is what I was thinking when I wrote the story
