### ISSUE TITLE
Change README.MD to describe the project

### ISSUE THREAD

**Issue by Pegmode** [CMPUT301W21T03/Experiment-Automata#236]
README.MD should be updated to have a better description of the project. People viewing this repo wont understand what this project contains. I like to add a couple of images and a brief description.

**Comment by TurtleSquad007** [comment]
Isn't that what the wiki is for?

**Comment by Pegmode** [comment]
You assume that someone will go through the  effort of looking through the wiki? All we need is a brief description and like a screenshot.

**Comment by TurtleSquad007** [comment]
Yup fair enough. After finals if no one has done, I'll do it.
