### ISSUE TITLE
API - Experiments Get/Post Firestore

### ISSUE THREAD

**Issue by NickNissen** [CMPUT301W21T03/Experiment-Automata#47]
Rationale:
Create API endpoints and functionality for Experiments in Firestore.

Story Points:
4

Risk Level:
High

**Comment by Pegmode** [comment]
Basic requirements have been implemented in [experimentFirestoreIntegration branch](https://github.com/CMPUT301W21T03/Experiment-Automata/tree/experimentFirestoreIntegration) but we are waiting for a unit test solution before merging. See https://github.com/CMPUT301W21T03/Experiment-Automata/pull/94.

**Comment by Pegmode** [comment]
Firestore does not update upon editing experiment
