### ISSUE TITLE
Login-Story

### ISSUE THREAD

**Issue by TurtleSquad007** [CMPUT301W21T03/Experiment-Automata#7]
Rationale:
When a user first opens the app, assign a UUID and store that UUID in local memory. The User can choose to update their profile or not. At no time does the user need to login, and auth is not within the scope of this project at this time.

Estimated Size in Story Points:
1

Risk Level: 
low

**Comment by NickNissen** [comment]
May need to consider Authentication of future API calls, so storage to auth tokens may be required. If this is the case, add an additional Story for that funcitonality.
